# Generated by Django 5.1.1 on 2024-12-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profession', models.CharField(max_length=35)),
                ('about_me', models.CharField(max_length=25)),
                ('photo', models.ImageField(upload_to='about_me/')),
                ('back_round_img', models.ImageField(upload_to='about_me/')),
            ],
        ),
        migrations.CreateModel(
            name='ImgReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='review/')),
                ('feedback', models.CharField(help_text='отзывы моих клиентов', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='MainWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=35)),
                ('main_text', models.CharField(max_length=100)),
                ('publication', models.PositiveSmallIntegerField(help_text='количества публикации')),
                ('follower', models.CharField(help_text='количества подписчиков', max_length=25)),
                ('subscription', models.PositiveSmallIntegerField(help_text='количества людей на которые вы подписаны ')),
            ],
        ),
    ]
