# Generated by Django 5.1.4 on 2024-12-19 16:49

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('bio_en', models.TextField(null=True)),
                ('bio_ru', models.TextField(null=True)),
                ('bio_ky', models.TextField(null=True)),
                ('profession', models.CharField(max_length=35)),
                ('profession_en', models.CharField(max_length=35, null=True)),
                ('profession_ru', models.CharField(max_length=35, null=True)),
                ('profession_ky', models.CharField(max_length=35, null=True)),
                ('about_me', models.CharField(max_length=25)),
                ('about_me_en', models.CharField(max_length=25, null=True)),
                ('about_me_ru', models.CharField(max_length=25, null=True)),
                ('about_me_ky', models.CharField(max_length=25, null=True)),
                ('photo', models.ImageField(upload_to='about_me/')),
                ('back_round_img', models.ImageField(upload_to='about_me/')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('title_en', models.CharField(max_length=512, null=True)),
                ('title_ru', models.CharField(max_length=512, null=True)),
                ('title_ky', models.CharField(max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=512)),
                ('duration_en', models.CharField(max_length=512, null=True)),
                ('duration_ru', models.CharField(max_length=512, null=True)),
                ('duration_ky', models.CharField(max_length=512, null=True)),
                ('format', models.CharField(max_length=512)),
                ('format_en', models.CharField(max_length=512, null=True)),
                ('format_ru', models.CharField(max_length=512, null=True)),
                ('format_ky', models.CharField(max_length=512, null=True)),
                ('feedback', models.CharField(max_length=512)),
                ('feedback_en', models.CharField(max_length=512, null=True)),
                ('feedback_ru', models.CharField(max_length=512, null=True)),
                ('feedback_ky', models.CharField(max_length=512, null=True)),
                ('price', models.PositiveSmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=35)),
                ('profession_en', models.CharField(max_length=35, null=True)),
                ('profession_ru', models.CharField(max_length=35, null=True)),
                ('profession_ky', models.CharField(max_length=35, null=True)),
                ('main_text', models.CharField(max_length=100)),
                ('main_text_en', models.CharField(max_length=100, null=True)),
                ('main_text_ru', models.CharField(max_length=100, null=True)),
                ('main_text_ky', models.CharField(max_length=100, null=True)),
                ('publication', models.PositiveSmallIntegerField(help_text='количества публикации')),
                ('follower', models.CharField(help_text='количества подписчиков', max_length=25)),
                ('follower_en', models.CharField(help_text='количества подписчиков', max_length=25, null=True)),
                ('follower_ru', models.CharField(help_text='количества подписчиков', max_length=25, null=True)),
                ('follower_ky', models.CharField(help_text='количества подписчиков', max_length=25, null=True)),
                ('subscription', models.PositiveSmallIntegerField(help_text='количества людей на которые вы подписаны ')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('telegram', models.CharField(max_length=25)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(help_text='отзывы моих клиентов', max_length=35)),
                ('feedback_en', models.CharField(help_text='отзывы моих клиентов', max_length=35, null=True)),
                ('feedback_ru', models.CharField(help_text='отзывы моих клиентов', max_length=35, null=True)),
                ('feedback_ky', models.CharField(help_text='отзывы моих клиентов', max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation_Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=512)),
                ('keys_en', models.CharField(max_length=512, null=True)),
                ('keys_ru', models.CharField(max_length=512, null=True)),
                ('keys_ky', models.CharField(max_length=512, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_keys', to='phisology.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='review_img/')),
                ('review_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='phisology.review')),
            ],
        ),
    ]
