# Generated by Django 5.1.3 on 2025-01-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='text1',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='explanations',
            new_name='text2',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='text',
            new_name='text3',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='text_last',
            new_name='text4',
        ),
    ]
