# Generated by Django 5.1.1 on 2024-12-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='review_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(help_text='отзывы моих клиентов', max_length=35)),
            ],
        ),
        migrations.DeleteModel(
            name='ImgReview',
        ),
        migrations.AddField(
            model_name='img',
            name='review_connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='phisology.review'),
        ),
    ]
