# Generated by Django 5.1.4 on 2024-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainworld',
            name='main_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mainworld',
            name='main_text_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainworld',
            name='main_text_ky',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainworld',
            name='main_text_ru',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
