# Generated by Django 5.1.3 on 2025-01-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0002_rename_description_services_text1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgservices',
            name='services_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imgservices',
            name='services_text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imgservices',
            name='services_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='my_services',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='my_services',
            name='title_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='my_services',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='questions_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='questions_ky',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='questions_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_services_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_services_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_services_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text1_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text2_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text3_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text3_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text4_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text4_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text4_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services_keys',
            name='keys_en',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='services_keys',
            name='keys_ky',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='services_keys',
            name='keys_ru',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='services_keys',
            name='services_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_keys', to='phisology.services'),
        ),
    ]
