# Generated by Django 5.1.4 on 2024-12-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0003_alter_registration_country_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='feedback',
            field=models.CharField(help_text='Обратная свзять', max_length=512),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='feedback_en',
            field=models.CharField(help_text='Обратная свзять', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='feedback_ky',
            field=models.CharField(help_text='Обратная свзять', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='feedback_ru',
            field=models.CharField(help_text='Обратная свзять', max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_services', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveSmallIntegerField(default=200)),
                ('my_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='phisology.my_services')),
            ],
        ),
    ]
