# Generated by Django 5.1.4 on 2024-12-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0003_alter_registration_country_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='feedback',
            field=models.CharField(help_text='Обратная свзять', max_length=512),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='feedback_en',
            field=models.CharField(help_text='Обратная свзять', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='feedback_ky',
            field=models.CharField(help_text='Обратная свзять', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='feedback_ru',
            field=models.CharField(help_text='Обратная свзять', max_length=512, null=True),
        ),
    ]
