# Generated by Django 5.1.3 on 2025-01-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0004_public_offer_safety_public_offertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_name', models.CharField(max_length=55)),
                ('safety_name_en', models.CharField(max_length=55, null=True)),
                ('safety_name_ru', models.CharField(max_length=55, null=True)),
                ('safety_name_ky', models.CharField(max_length=55, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='public_offer',
            name='main_en',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='public_offer',
            name='main_ky',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='public_offer',
            name='main_ru',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='public_offertext',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_offertext',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_offertext',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_offertext',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='public_offertext',
            name='title_ky',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='public_offertext',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='safety',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safety',
            name='text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safety',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safety',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='safety',
            name='title_ky',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='safety',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
