# Generated by Django 5.1.3 on 2025-01-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0005_safetymain_public_offer_main_en_public_offer_main_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='patterns',
        ),
        migrations.AddField(
            model_name='pattern',
            name='services_connect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pattern', to='phisology.services'),
            preserve_default=False,
        ),
    ]
