# Generated by Django 5.1.3 on 2025-01-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0006_remove_services_patterns_pattern_services_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='services_connect',
        ),
        migrations.AddField(
            model_name='pattern',
            name='services_connect',
            field=models.ManyToManyField(related_name='pattern', to='phisology.services'),
        ),
    ]
