# Generated by Django 5.1.3 on 2025-01-13 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0007_remove_pattern_services_connect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='services_connect',
        ),
        migrations.AddField(
            model_name='services',
            name='pattern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phisology.pattern'),
            preserve_default=False,
        ),
    ]
