# Generated by Django 5.1.3 on 2025-01-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0008_remove_pattern_services_connect_services_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
