# Generated by Django 5.1.3 on 2025-01-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisology', '0009_services_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainworld',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='main_photo/'),
        ),
    ]
